# Generated by Django 6.0.7 on 2026-07-31 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("full_description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=80)),
                (
                    "starting_price_inr",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("city", models.CharField(default="Bhubaneswar", max_length=80)),
                ("state", models.CharField(default="Odisha", max_length=80)),
                ("active", models.BooleanField(default=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Locality-specific content, 250+ words before publishing a page for this area.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review_text", models.TextField()),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        default="direct",
                        help_text="'google' or 'direct'",
                        max_length=20,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Only approved+genuine reviews should ever render on the live site.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "-review_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=120)),
                ("preferred_datetime", models.DateTimeField(blank=True, null=True)),
                ("urgency", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField(blank=True)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website_form", "Website form"),
                            ("phone", "Phone call"),
                            ("whatsapp_direct", "WhatsApp direct message"),
                            ("other", "Other"),
                        ],
                        default="website_form",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("confirmed_visit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "quoted_amount_inr",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.service",
                    ),
                ),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.technician",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("full_address", models.CharField(blank=True, max_length=255)),
                ("locality", models.CharField(max_length=120)),
                ("service_label", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website_form", "Website form"),
                            ("phone", "Phone call"),
                            ("whatsapp_direct", "WhatsApp direct message"),
                            ("other", "Other"),
                        ],
                        default="website_form",
                        max_length=20,
                    ),
                ),
                (
                    "contact_preference",
                    models.CharField(default="whatsapp", max_length=20),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        help_text="e.g. emergency / today / this week / flexible",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("submission_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "whatsapp_alert_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("n_a", "Not applicable"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "whatsapp_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Meta's message ID, useful for delivery-status webhooks later.",
                        max_length=100,
                    ),
                ),
                (
                    "email_alert_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("n_a", "Not applicable"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.technician",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_lead_status_a96776_idx",
                    )
                ],
            },
        ),
    ]
