# Generated by Django 6.0.7 on 2026-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_throttle_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='consent_notice_version',
            field=models.CharField(blank=True, help_text='Version stamp of the consent wording shown to the customer. Read-only evidence - never edit it.', max_length=32),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='email_alert_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('n_a', 'Not applicable')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_time_slot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='service_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='whatsapp_alert_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('n_a', 'Not applicable')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_notice_version',
            field=models.CharField(blank=True, help_text='Version stamp of the consent wording shown to the customer. Read-only evidence - never edit it.', max_length=32),
        ),
    ]
