server {
    listen 80;
    
    # TODO: Add your domain here later once configured (e.g. example.com www.example.com)
    # For now, '_' is a catch-all that will accept requests to the EC2 instance IP.
    server_name _; 

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        # Assuming the project is in /home/ubuntu/project-plumb
        # Django's collectstatic puts files in /home/ubuntu/project-plumb/staticfiles
        alias /home/ubuntu/project-plumb/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/project_plumb.sock;
    }
    
    # TODO: Once a domain exists, run Certbot (Let's Encrypt) to configure SSL.
    # It will automatically modify this block and add the necessary SSL certificates.
}
